#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: Michele Memoli
title: Interviews with Myself
subtitle: Experiences of running a design agency
url: http://mmmo.li

# Short bio or description (displayed in the header)
description: Experiences of running a design agency

sass:
  style: :compressed

baseurl: ''
instagram_username: '@m_mmoli'
instagram_link: 'https://www.instagram.com/m_mmoli/'
twitter_username: '@m_mmoli'
twitter_link: 'https://twitter.com/m_mmoli'
github_username:  '@mmmoli'
github_link:  'https://github.com/mmmoli'
linkedin_link:  'https://uk.linkedin.com/in/michele-memoli-91b19a7'
medium_link: 'https://medium.com/@mmmoli'

permalink: /blog/:categories/:title/

# Build settings
markdown: kramdown
safe: false

sass:
  style: compressed

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock
  - scripts
  - README.md

gems:
  - jekyll-sitemap
