#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: Michele Memoli
title: Interviews with Myself
subtitle: Experiences of running a design agency
url: http://mmmo.li

# Short bio or description (displayed in the header)
description: Experiences of running a design agency

sass:
  style: :compressed

baseurl: ''
instagram_username: '@m_mmoli'
instagram_link: 'https://www.instagram.com/m_mmoli/'
twitter_username: '@100Shapes'
github_username:  '@100Shapes'
address: '13 Hawley Cres., Camden, London, NW1 8NP'
address_link: https://goo.gl/maps/YVr9ih4MLZL2
permalink: /blog/:categories/:title/

# Build settings
markdown: kramdown
safe: false

sass:
  style: compressed

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock
  - scripts
  - README.md

gems:
  - jekyll-sitemap
